name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Descargando dependencias
      run: npm install
    - name: Creando carpeta dist
      run: ng build --prod
    - name: Deployando en firebase
      run: firebase deploy
