name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script Un saludo
      run: echo Hola mundo, estoy usando Github Actions!
    - name: Run a multi-line script: Otro saludo multilinea
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        echo By @schicoma
